kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: birthday-app
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: backend
        app: birthday-app
        env: prod
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=sre-test-203806:europe-west1:storage=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      - name: backend
        image: gcr.io/sre-test-203806/birthday-app:live
        env:
        - name: DB_CONN
          value: 127.0.0.1:3306:app
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /statusz
            port: 80
        command: ['python3', '-m', 'aiohttp.web', '-H', '0.0.0.0', '-P', '80', 'app.main:run']
        ports:
        - name: frontend
          containerPort: 80
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
