kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: birthday-app-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: backend
        app: birthday-app
        env: dev
    spec:
      containers:
      - name: backend
        image: gcr.io/sre-test-203806/birthday-app:master.latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /statusz
            port: 80
        command: ['python3', '-m', 'aiohttp.web', '-H', '0.0.0.0', '-P', '80', 'app.main:run']
        ports:
        - name: backend
          containerPort: 80
